### ISSUE TITLE
getent used with more than one entity

### ISSUE THREAD

**Issue by TheFrenchGhosty** [PussTheCat-org/PussTheCat.org-Cod4x-KTK#60] opened 2021-04-23 11:53 UTC
```
******* script runtime error *******
getent used with more than one entity: (file 'maps/mp/_helicopter.gsc', line 106)
  startnode = getent( loop_start[i].target, "targetname" );
              *
called from:
(file 'maps/mp/_helicopter.gsc', line 158)
 heli_path_graph();
 *
called from:
(file 'maps/mp/gametypes/_helipath.gsc', line 213)
    maps\mp\_helicopter::init();
    *
called from:
(file 'maps/mp/gametypes/_general.gsc', line 54)
 thread maps\mp\gametypes\_helipath::init();
        *
called from:
(file 'maps/mp/gametypes/_globallogic.gsc', line 4127)
 thread maps\mp\gametypes\_general::main();
        *
called from:
(file 'maps/mp/gametypes/_callbacksetup.gsc', line 15)
  [[level.callbackStartGameType]]();
          *
started from:
(file 'maps/mp/gametypes/_callbacksetup.gsc', line 10)
CodeCallback_StartGameType()
*
************************************
```

It crashed the server.

**Comment by VikingKampfsau** [comment] 2021-04-25 15:07
I am not able to reproduce this error, but i think it's a map fault.

mp_bubba works so it's not mp_bubba this time

**Comment by VikingKampfsau** [comment] 2021-04-30 06:45
duplicate issue, i will close this and use the other one for further comments

**Closed by VikingKampfsau** 2021-04-30 06:45 UTC
Labels: bug
